### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by LightningMods** [SilicaAndPina/UnityTools#1]
It doesnt work i tried to put a eboot.self and eboot.bin in C:\.. and it doesnt work

![image](https://user-images.githubusercontent.com/34066913/39613246-f1d1a390-4f33-11e8-8ed8-bb0087ec89e4.png)

**Comment by SilicaAndPina** [comment]
eboot.bin and eboot.self? yea that will probably confuse it :d

**Comment by SilicaAndPina** [comment]
Fixed
